server {
    listen 80;
    server_name moscatel.ddns.net 18.220.171.193;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name moscatel.ddns.net;

    ssl_certificate /etc/letsencrypt/live/moscatel.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/moscatel.ddns.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /opt/printflow/staticfiles/;
    }

    location /media/ {
        alias /opt/printflow/media/;
    }

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/gunicorn-printflow/gunicorn.sock;
    }
}
