# Generated by Django 5.2.7 on 2025-10-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='printers.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='printers.city')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='printers.printermodel')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='printers.sector')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
