# Generated by Django 5.2.7 on 2025-10-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0005_collaborator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="serial_number",
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
