# Generated by Django 5.2.7 on 2025-10-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0006_alter_printer_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="printermaintenance",
            name="replacement_installed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
