# Generated by Django 5.2.7 on 2026-04-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0009_base_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='printer',
            name='patrimony_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
