# Generated by Django 5.0.1 on 2026-04-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0010_printer_barcode_printer_patrimony_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='barcode_scan_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='serial_number_scan_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
