# Generated by Django 5.0.1 on 2026-04-09 01:38

import django.db.models.deletion
from django.db import migrations, models


def seed_maintenance_statuses(apps, schema_editor):
    MaintenanceStatus = apps.get_model("printers", "MaintenanceStatus")
    PrinterMaintenance = apps.get_model("printers", "PrinterMaintenance")

    in_progress_status, _ = MaintenanceStatus.objects.get_or_create(
        name="Em manutencao",
        defaults={"flow": "in_progress"},
    )
    completed_status, _ = MaintenanceStatus.objects.get_or_create(
        name="Disponivel",
        defaults={"flow": "completed"},
    )

    PrinterMaintenance.objects.filter(status="in_progress").update(status_catalog=in_progress_status)
    PrinterMaintenance.objects.filter(status="completed").update(status_catalog=completed_status)


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0012_backfill_printer_scan_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Local de manutencao',
                'verbose_name_plural': 'Locais de manutencao',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('flow', models.CharField(choices=[('in_progress', 'Em manutencao'), ('completed', 'Disponivel')], default='in_progress', max_length=20)),
            ],
            options={
                'verbose_name': 'Status de manutencao',
                'verbose_name_plural': 'Status de manutencao',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='printermaintenance',
            options={'ordering': ['-started_at', '-created_at'], 'verbose_name': 'Manutencao de impressora', 'verbose_name_plural': 'Manutencoes de impressoras'},
        ),
        migrations.AlterField(
            model_name='printermaintenance',
            name='maintenance_location_type',
            field=models.CharField(choices=[('lessor', 'Loja responsavel'), ('third_party', 'Terceirizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printermaintenance',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em manutencao'), ('completed', 'Disponivel')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='printermaintenance',
            name='maintenance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='printers.maintenanceprovider'),
        ),
        migrations.AddField(
            model_name='printermaintenance',
            name='status_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='printers.maintenancestatus'),
        ),
        migrations.RunPython(seed_maintenance_statuses, migrations.RunPython.noop),
    ]
