# Generated by Django 5.0.1 on 2026-04-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0013_maintenanceprovider_maintenancestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printermaintenance',
            name='solution_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PrinterInstallationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=120)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('removed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printer_installation_history', to='printers.city')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_history', to='printers.printer')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printer_installation_history', to='printers.sector')),
            ],
            options={
                'verbose_name': 'Historico de instalacao',
                'verbose_name_plural': 'Historicos de instalacao',
                'ordering': ['-installed_at', '-created_at'],
            },
        ),
    ]
