# Generated by Django 5.2.7 on 2026-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0016_collaborator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printerinstallationhistory',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printerinstallationhistory',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printermaintenance',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printermaintenance',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
