# Generated by Django 5.2.7 on 2026-04-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0017_alter_printer_installed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcatalog',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'Local base', 'verbose_name_plural': 'Locais base'},
        ),
        migrations.AddField(
            model_name='locationcatalog',
            name='address',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='locationcatalog',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_catalog_items', to='printers.city'),
        ),
        migrations.AddField(
            model_name='locationcatalog',
            name='location_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationcatalog',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationcatalog',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='locationcatalog',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='locationcatalog',
            unique_together={('city', 'name')},
        ),
    ]
