# Generated by Django 5.2.7 on 2026-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0018_alter_locationcatalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcatalog',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
