from django.urls import path

from . import views

app_name = "printers"

urlpatterns = [
    path("entrar/", views.AppLoginView.as_view(), name="login"),
    path("sair/", views.app_logout, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("printers/", views.printer_list, name="printer-list"),
    path("printers/novo/", views.printer_create, name="printer-create"),
    path("printers/<int:pk>/", views.printer_detail, name="printer-detail"),
    path("printers/<int:pk>/editar/", views.printer_update, name="printer-update"),
    path("printers/<int:pk>/excluir/", views.printer_delete, name="printer-delete"),
    path("cidades/", views.city_list, name="city-list"),
    path("cidades/nova/", views.city_create, name="city-create"),
    path("cidades/<int:pk>/editar/", views.city_update, name="city-update"),
    path("cidades/<int:pk>/excluir/", views.city_delete, name="city-delete"),
    path("setores/", views.sector_list, name="sector-list"),
    path("setores/base/", views.sector_catalog_list, name="sector-catalog-list"),
    path("setores/base/novo/", views.sector_catalog_create, name="sector-catalog-create"),
    path("setores/base/<int:pk>/editar/", views.sector_catalog_update, name="sector-catalog-update"),
    path("setores/base/<int:pk>/excluir/", views.sector_catalog_delete, name="sector-catalog-delete"),
    path("setores/locais-base/", views.location_catalog_list, name="location-catalog-list"),
    path("setores/locais-base/novo/", views.location_catalog_create, name="location-catalog-create"),
    path("setores/locais-base/<int:pk>/editar/", views.location_catalog_update, name="location-catalog-update"),
    path("setores/locais-base/<int:pk>/excluir/", views.location_catalog_delete, name="location-catalog-delete"),
    path("setores/vinculos/", views.sector_binding_list, name="sector-binding-list"),
    path("setores/vinculos/novo/", views.sector_create, name="sector-create"),
    path("setores/vinculos/<int:pk>/editar/", views.sector_update, name="sector-update"),
    path("setores/vinculos/<int:pk>/excluir/", views.sector_delete, name="sector-delete"),
    path("modelos/", views.model_list, name="model-list"),
    path("modelos/novo/", views.model_create, name="model-create"),
    path("modelos/<int:pk>/editar/", views.model_update, name="model-update"),
    path("modelos/<int:pk>/excluir/", views.model_delete, name="model-delete"),
    path("manutencoes/", views.maintenance_list, name="maintenance-list"),
    path("manutencoes/nova/", views.maintenance_create, name="maintenance-create"),
    path("manutencoes/<int:pk>/editar/", views.maintenance_update, name="maintenance-update"),
    path("manutencoes/status/", views.maintenance_status_list, name="maintenance-status-list"),
    path("manutencoes/status/novo/", views.maintenance_status_create, name="maintenance-status-create"),
    path("manutencoes/status/<int:pk>/editar/", views.maintenance_status_update, name="maintenance-status-update"),
    path("manutencoes/status/<int:pk>/excluir/", views.maintenance_status_delete, name="maintenance-status-delete"),
    path("manutencoes/locais/", views.maintenance_provider_list, name="maintenance-provider-list"),
    path("manutencoes/locais/novo/", views.maintenance_provider_create, name="maintenance-provider-create"),
    path("manutencoes/locais/<int:pk>/editar/", views.maintenance_provider_update, name="maintenance-provider-update"),
    path("manutencoes/locais/<int:pk>/excluir/", views.maintenance_provider_delete, name="maintenance-provider-delete"),
    path("colaboradores/", views.collaborator_list, name="collaborator-list"),
    path("colaboradores/novo/", views.collaborator_create, name="collaborator-create"),
]
